spring.application.name=backend

# 1. Cấu hình kết nối MySQL Server
spring.datasource.url=jdbc:mysql://localhost:3306/english_center?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Anhnhat413@

# 2. Cấu hình JPA / Hibernate để làm việc với bảng
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect