spring.application.name=backend

# 1. Cấu hình kết nối MySQL Server
spring.datasource.url=jdbc:mysql://localhost:3306/english_center?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=Anhnhat413@

# 2. Cấu hình JPA / Hibernate để làm việc với bảng
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# 3. Cấu hình hiển thị thông tin lỗi chi tiết cho Frontend nhận diện
server.error.include-message=always

# 4. Cấu hình tăng giới hạn kích thước tải tệp tin lên 50MB (phục vụ Audio/Document)
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB